### ISSUE TITLE
sommelier q gravity unbatched-send-to-ethereums panics

### ISSUE THREAD

**Issue by jackzampolin** [PeggyJV/sommelier#112]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/peggyjv/gravity-bridge/module/x/gravity/client/cli.CmdUnbatchedSendToEthereums.func1(0xc0011c8500, 0x328ed98, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/peggyjv/gravity-bridge/module@v0.3.5/x/gravity/client/cli/query.go:667 +0x3f4
github.com/spf13/cobra.(*Command).execute(0xc0011c8500, 0x328ed98, 0x0, 0x0, 0xc0011c8500, 0x328ed98)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0010c0780, 0x0, 0x0, 0xc0010bcf60)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc0010c0780, 0xc0010bcf60, 0x1d, 0x24a9618, 0xc0010d93c0)
	/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x285
main.main()
	/home/runner/work/sommelier/sommelier/cmd/sommelier/main.go:14 +0x45

**Comment by cbrit** [comment]
This is a bug in the gravity module CLI which is fixed by this PR: https://github.com/PeggyJV/gravity-bridge/pull/466
